stages:
  - build
  - deploy

maven-build:
  image: maven:3.6.3-openjdk-15-slim
  stage: build
  script: "mvn install --batch-mode"
  artifacts:
    paths:
      - target/*.jar

deploy-maven-central:
  image: maven:3.6.3-openjdk-15-slim
  stage: deploy
  script:
    - echo "test"
  only:
    - release*
