name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Add GPG sign
        run: echo ${{ secrets.MAVEN_SIGN }} | base64 -d >> ~/.m2/mvn_sign.key && gpg --batch --import ~/.m2/mvn_sign.key
      - name: Add maven settings.xml
        run:  echo ${{ secrets.MAVEN_SETTINGS_FILE }} | base64 -d >> ~/.m2/settings.xml && mvn install --batch-mode
      - name: Build with Maven
        run: mvn install --batch-mode